/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TimeTrackingImport } from './routes/time-tracking'
import { Route as ReportsImport } from './routes/reports'
import { Route as IncomeExpensesImport } from './routes/income-expenses'
import { Route as GoalsImport } from './routes/goals'
import { Route as BudgetsImport } from './routes/budgets'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const TimeTrackingRoute = TimeTrackingImport.update({
  id: '/time-tracking',
  path: '/time-tracking',
  getParentRoute: () => rootRoute,
} as any)

const ReportsRoute = ReportsImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRoute,
} as any)

const IncomeExpensesRoute = IncomeExpensesImport.update({
  id: '/income-expenses',
  path: '/income-expenses',
  getParentRoute: () => rootRoute,
} as any)

const GoalsRoute = GoalsImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRoute,
} as any)

const BudgetsRoute = BudgetsImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/budgets': {
      id: '/budgets'
      path: '/budgets'
      fullPath: '/budgets'
      preLoaderRoute: typeof BudgetsImport
      parentRoute: typeof rootRoute
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsImport
      parentRoute: typeof rootRoute
    }
    '/income-expenses': {
      id: '/income-expenses'
      path: '/income-expenses'
      fullPath: '/income-expenses'
      preLoaderRoute: typeof IncomeExpensesImport
      parentRoute: typeof rootRoute
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsImport
      parentRoute: typeof rootRoute
    }
    '/time-tracking': {
      id: '/time-tracking'
      path: '/time-tracking'
      fullPath: '/time-tracking'
      preLoaderRoute: typeof TimeTrackingImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/budgets': typeof BudgetsRoute
  '/goals': typeof GoalsRoute
  '/income-expenses': typeof IncomeExpensesRoute
  '/reports': typeof ReportsRoute
  '/time-tracking': typeof TimeTrackingRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/budgets': typeof BudgetsRoute
  '/goals': typeof GoalsRoute
  '/income-expenses': typeof IncomeExpensesRoute
  '/reports': typeof ReportsRoute
  '/time-tracking': typeof TimeTrackingRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/budgets': typeof BudgetsRoute
  '/goals': typeof GoalsRoute
  '/income-expenses': typeof IncomeExpensesRoute
  '/reports': typeof ReportsRoute
  '/time-tracking': typeof TimeTrackingRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/budgets'
    | '/goals'
    | '/income-expenses'
    | '/reports'
    | '/time-tracking'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/budgets'
    | '/goals'
    | '/income-expenses'
    | '/reports'
    | '/time-tracking'
  id:
    | '__root__'
    | '/'
    | '/budgets'
    | '/goals'
    | '/income-expenses'
    | '/reports'
    | '/time-tracking'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BudgetsRoute: typeof BudgetsRoute
  GoalsRoute: typeof GoalsRoute
  IncomeExpensesRoute: typeof IncomeExpensesRoute
  ReportsRoute: typeof ReportsRoute
  TimeTrackingRoute: typeof TimeTrackingRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BudgetsRoute: BudgetsRoute,
  GoalsRoute: GoalsRoute,
  IncomeExpensesRoute: IncomeExpensesRoute,
  ReportsRoute: ReportsRoute,
  TimeTrackingRoute: TimeTrackingRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/budgets",
        "/goals",
        "/income-expenses",
        "/reports",
        "/time-tracking"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/budgets": {
      "filePath": "budgets.tsx"
    },
    "/goals": {
      "filePath": "goals.tsx"
    },
    "/income-expenses": {
      "filePath": "income-expenses.tsx"
    },
    "/reports": {
      "filePath": "reports.tsx"
    },
    "/time-tracking": {
      "filePath": "time-tracking.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
